name: Update Age

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-age:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Calculate Age
        id: calc
        run: |
          BIRTHDAY="1993-07-16"
          NOW=$(date +%s)
          BIRTH=$(date -d "$BIRTHDAY" +%s)
          SECONDS_IN_YEAR=31557600
          AGE=$(echo "($NOW - $BIRTH) / $SECONDS_IN_YEAR" | bc)
          echo "age=$AGE" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          AGE=${{ steps.calc.outputs.age }}
          sed -i "s/^My Age:.*/My Age: $AGE/" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          if ! git diff --cached --quiet; then
            git commit -m "Update age to ${{ steps.calc.outputs.age }}"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          else
            echo "No changes to commit"
          fi
